version: "3"
services:
    nginx:
   #   restart: always
      build:
        context: ./nginx
        dockerfile: ./Dockerfile
      ports:
        - "8080:8080"


    app:
      build: 
        context: ./app
        dockerfile: ./Dockerfile
      ports:
        - "3000:3000"
     