version: "3"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    depends_on:
      - app
    ports:
      - "8000:8000"

  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    depends_on:
      - db
    expose:
      - "5000"
    ports:
      - "5000:5000"

  adminer:
    image: adminer
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    expose:
      - "8080"
    ports:
      - 8080:8080
    links:
      - db

  db:
    build:
      context: ./db
    ports:
      - 5555:3306
    environment:
      - MARIADB_ROOT_PASSWORD=example
      - MARIADB_DATABASE=joke_db
      - MARIADB_USER=root
      - MARIADB_PASSWORD=example

    command: mysqld --datadir=/internal/db_storage
    volumes:
      - ./db/db_storage:/internal/db_storage
