version: "3"
services:
    nginx:
   #   restart: always
      build:
        context: ./nginx
        dockerfile: ./Dockerfile
      depends_on:
        - app
      ports:
        - "8080:8080"


    app:
      build: 
        context: ./app
        dockerfile: ./Dockerfile
      expose: 
        - "5000"
      ports:
        - "3000:3000"
        - "5000:5000"
     